apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-service
  template:
    metadata:
      name: hello-service
      labels:
        app: hello-service
        version: v1
    spec:
        containers:
          image: harbor/hello:1.0
          imagePullPolicy: IfNotPresent
          name: hello-service
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
